# Generated by Django 4.1.3 on 2023-07-08 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hammadde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rawMaterialName",
                    models.CharField(max_length=200, verbose_name="Hammadde Tipi"),
                ),
                (
                    "isScrap",
                    models.BooleanField(
                        choices=[(1, "EVET"), (0, "HAYIR")],
                        verbose_name="Değersiz / Hurda mı?",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kantar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kantar1", models.FloatField(verbose_name="Kantar 1")),
                ("kantar2", models.FloatField(verbose_name="Kantar 2")),
                (
                    "kantar3",
                    models.FloatField(blank=True, null=True, verbose_name="Kantar 3"),
                ),
                (
                    "kantar4",
                    models.FloatField(blank=True, null=True, verbose_name="Kantar 4"),
                ),
                (
                    "kantar5",
                    models.FloatField(blank=True, null=True, verbose_name="Kantar 5"),
                ),
                (
                    "kantar6",
                    models.FloatField(blank=True, null=True, verbose_name="Kantar 6"),
                ),
                (
                    "tarih",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="Tarih",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tedarikci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Ad")),
                ("surname", models.CharField(max_length=50, verbose_name="Soyad")),
                (
                    "idNumber",
                    models.CharField(max_length=25, verbose_name="TC Kimlik No"),
                ),
                ("adress", models.CharField(max_length=200, verbose_name="Adres")),
                ("tax", models.CharField(max_length=100, verbose_name="Vergi Dairesi")),
                ("mail1", models.EmailField(max_length=100, verbose_name="E-mail 1")),
                ("mail2", models.EmailField(max_length=100, verbose_name="E-mail 2")),
                (
                    "phoneNumber1",
                    models.CharField(max_length=20, verbose_name="Telefon 1"),
                ),
                (
                    "phoneNumber2",
                    models.CharField(max_length=20, verbose_name="Telefon 2"),
                ),
                ("IBAN", models.CharField(max_length=100, verbose_name="IBAN")),
                (
                    "bankNumber",
                    models.CharField(
                        max_length=100, verbose_name="Banka Hesap Numarası"
                    ),
                ),
                ("bank", models.CharField(max_length=100, verbose_name="Banka")),
                (
                    "companyName",
                    models.CharField(max_length=100, verbose_name="Şirket"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MalGiris",
            fields=[
                (
                    "alimKodu",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tarih",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Tarih"
                    ),
                ),
                ("miktar1", models.FloatField(verbose_name="Ağırlık - 1")),
                ("birimFiyat1", models.FloatField(verbose_name="Birim Fiyat - 1")),
                (
                    "miktar1a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 1a"
                    ),
                ),
                (
                    "birimFiyat1a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 1a"
                    ),
                ),
                (
                    "miktar1b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 1b"
                    ),
                ),
                (
                    "birimFiyat1b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 1b"
                    ),
                ),
                (
                    "miktar1c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 1c"
                    ),
                ),
                (
                    "birimFiyat1c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 1c"
                    ),
                ),
                (
                    "miktar2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 2"
                    ),
                ),
                (
                    "birimFiyat2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 2"
                    ),
                ),
                (
                    "miktar2a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 2a"
                    ),
                ),
                (
                    "birimFiyat2a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 2a"
                    ),
                ),
                (
                    "miktar2b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 2b"
                    ),
                ),
                (
                    "birimFiyat2b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 2b"
                    ),
                ),
                (
                    "miktar2c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 2c"
                    ),
                ),
                (
                    "birimFiyat2c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 2c"
                    ),
                ),
                (
                    "miktar3",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 3"
                    ),
                ),
                (
                    "birimFiyat3",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 3"
                    ),
                ),
                (
                    "miktar3a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 3a"
                    ),
                ),
                (
                    "birimFiyat3a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 3a"
                    ),
                ),
                (
                    "miktar3b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 3b"
                    ),
                ),
                (
                    "birimFiyat3b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 3b"
                    ),
                ),
                (
                    "miktar3c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 3c"
                    ),
                ),
                (
                    "birimFiyat3c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 3c"
                    ),
                ),
                (
                    "miktar4",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 4"
                    ),
                ),
                (
                    "birimFiyat4",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 4"
                    ),
                ),
                (
                    "miktar4a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 4a"
                    ),
                ),
                (
                    "birimFiyat4a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 4a"
                    ),
                ),
                (
                    "miktar4b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 4b"
                    ),
                ),
                (
                    "birimFiyat4b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 4b"
                    ),
                ),
                (
                    "miktar4c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 4c"
                    ),
                ),
                (
                    "birimFiyat4c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 4c"
                    ),
                ),
                (
                    "miktar5",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 5"
                    ),
                ),
                (
                    "birimFiyat5",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 5"
                    ),
                ),
                (
                    "miktar5a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 5a"
                    ),
                ),
                (
                    "birimFiyat5a",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 5a"
                    ),
                ),
                (
                    "miktar5b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 5b"
                    ),
                ),
                (
                    "birimFiyat5b",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 5b"
                    ),
                ),
                (
                    "miktar5c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ağırlık - 5c"
                    ),
                ),
                (
                    "birimFiyat5c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birim Fiyat - 5c"
                    ),
                ),
                (
                    "mal1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal1",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 1",
                    ),
                ),
                (
                    "mal1a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal11a",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 1a",
                    ),
                ),
                (
                    "mal1b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal11b",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 1b",
                    ),
                ),
                (
                    "mal1c",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal11c",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 1c",
                    ),
                ),
                (
                    "mal2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal12",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 2",
                    ),
                ),
                (
                    "mal2a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal12a",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 2a",
                    ),
                ),
                (
                    "mal2b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal12b",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 2b",
                    ),
                ),
                (
                    "mal2c",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal12c",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 2c",
                    ),
                ),
                (
                    "mal3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal13",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 3",
                    ),
                ),
                (
                    "mal3a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal13a",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 3a",
                    ),
                ),
                (
                    "mal3b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal13b",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 3b",
                    ),
                ),
                (
                    "mal3c",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal13c",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 3c",
                    ),
                ),
                (
                    "mal4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal14",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 4",
                    ),
                ),
                (
                    "mal4a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal14a",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 4a",
                    ),
                ),
                (
                    "mal4b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal14b",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 4b",
                    ),
                ),
                (
                    "mal4c",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal14c",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 4c",
                    ),
                ),
                (
                    "mal5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal15",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 5",
                    ),
                ),
                (
                    "mal5a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal15a",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 5a",
                    ),
                ),
                (
                    "mal5b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal15b",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 5b",
                    ),
                ),
                (
                    "mal5c",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mal15c",
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü - 5c",
                    ),
                ),
                (
                    "tedarikEden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.tedarikci",
                        verbose_name="Tedarikçi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alimlar_Kirilim",
            fields=[
                (
                    "alimKodu",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.FloatField(verbose_name="Ağırlık (kg)")),
                (
                    "tarih",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Tarih"
                    ),
                ),
                ("birimFiyat", models.FloatField(verbose_name="Birim Fiyat")),
                ("alimKoduGenel", models.IntegerField(verbose_name="Alım Kodu")),
                (
                    "mal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü",
                    ),
                ),
                (
                    "tedarikEden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.tedarikci",
                        verbose_name="Tedarikçi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alimlar",
            fields=[
                (
                    "alimKodu",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("miktar", models.FloatField(verbose_name="Ağırlık (kg)")),
                (
                    "tarih",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Tarih"
                    ),
                ),
                ("birimFiyat", models.FloatField(verbose_name="Birim Fiyat")),
                ("alimKoduGenel", models.IntegerField(verbose_name="Alım Kodu")),
                (
                    "mal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü",
                    ),
                ),
                (
                    "tedarikEden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.tedarikci",
                        verbose_name="Tedarikçi",
                    ),
                ),
            ],
        ),
    ]
