# Generated by Django 4.2.2 on 2023-06-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tedarikci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Ad")),
                ("surname", models.CharField(max_length=50, verbose_name="Soyad")),
                (
                    "idNumber",
                    models.CharField(max_length=25, verbose_name="TC Kimlik No"),
                ),
                ("adress", models.CharField(max_length=200, verbose_name="Adres")),
                ("tax", models.CharField(max_length=100, verbose_name="Vergi Dairesi")),
                ("mail1", models.EmailField(max_length=100, verbose_name="E-mail 1")),
                ("mail2", models.EmailField(max_length=100, verbose_name="E-mail 2")),
                (
                    "phoneNumber1",
                    models.CharField(max_length=20, verbose_name="Telefon 1"),
                ),
                (
                    "phoneNumber2",
                    models.CharField(max_length=20, verbose_name="Telefon 2"),
                ),
                ("IBAN", models.CharField(max_length=100, verbose_name="IBAN")),
                (
                    "bankNumber",
                    models.CharField(
                        max_length=100, verbose_name="Banka Hesap Numarası"
                    ),
                ),
                ("bank", models.CharField(max_length=100, verbose_name="Banka")),
            ],
        ),
    ]
