# Generated by Django 4.2.2 on 2023-06-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hammadde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rawMaterialName",
                    models.CharField(max_length=200, verbose_name="Hammadde Tipi"),
                ),
                (
                    "isScrap",
                    models.BooleanField(
                        choices=[(1, "EVET"), (0, "HAYIR")],
                        verbose_name="Değersiz / Hurda mı?",
                    ),
                ),
            ],
        ),
    ]
