# Generated by Django 4.1.3 on 2023-07-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0002_remove_alimlar_kirilim_mal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kantar",
            name="tedarikci",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mainPage.tedarikci",
            ),
            preserve_default=False,
        ),
    ]
