# Generated by Django 4.2.2 on 2023-06-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0002_hammadde"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.IntegerField(verbose_name="Ağırlık (kg)")),
                ("tarih", models.DateTimeField(verbose_name="Tarih")),
                (
                    "mal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü",
                    ),
                ),
                (
                    "tedarikEden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.tedarikci",
                        verbose_name="Tedarikçi",
                    ),
                ),
            ],
        ),
    ]
