# Generated by Django 4.1.3 on 2023-07-08 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0003_kantar_tedarikci"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kantar",
            name="tedarikci",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mainPage.tedarikci",
                verbose_name="Tedarikçi",
            ),
        ),
        migrations.CreateModel(
            name="MalzemeGiris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brut", models.FloatField(verbose_name="Brüt Ağırlık")),
                ("hurda", models.FloatField(verbose_name="Hurda Ağırlık")),
                ("net", models.FloatField(verbose_name="Net Ağırlık")),
                ("birimFiyat", models.FloatField(verbose_name="Birim Fiyat")),
                (
                    "kantarId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.kantar",
                        verbose_name="Kantar ID",
                    ),
                ),
                (
                    "malzemeTipi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Tipi",
                    ),
                ),
            ],
        ),
    ]
