# Generated by Django 4.2.2 on 2023-06-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0003_buy"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Buy",
            new_name="Alimlar",
        ),
    ]
