# Generated by Django 4.2.2 on 2023-06-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0004_rename_buy_alimlar"),
    ]

    operations = [
        migrations.AddField(
            model_name="tedarikci",
            name="companyName",
            field=models.CharField(default=123, max_length=100, verbose_name="Şirket"),
            preserve_default=False,
        ),
    ]
