# Generated by Django 4.2.2 on 2023-07-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0004_alter_kantar_tedarikci_malzemegiris"),
    ]

    operations = [
        migrations.CreateModel(
            name="MalAlim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.FloatField(verbose_name="Ağırlık")),
                ("hurda", models.FloatField(verbose_name="Hurda")),
                ("birimFiyat", models.FloatField(verbose_name="Birim Fiyat")),
                (
                    "kantar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.kantar",
                        verbose_name="Kantar tartım numarası",
                    ),
                ),
                (
                    "mal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü",
                    ),
                ),
            ],
        ),
    ]
