# Generated by Django 4.2.2 on 2023-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0005_tedarikci_companyname"),
    ]

    operations = [
        migrations.AddField(
            model_name="alimlar",
            name="birimFiyat",
            field=models.IntegerField(default=12, verbose_name="Birim Fiyat"),
            preserve_default=False,
        ),
    ]
