# Generated by Django 4.2.2 on 2023-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0005_malalim"),
    ]

    operations = [
        migrations.AddField(
            model_name="kantar",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Not"),
        ),
    ]
