# Generated by Django 4.2.2 on 2023-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0006_kantar_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="musteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Ad")),
                ("surname", models.CharField(max_length=50, verbose_name="Soyad")),
                (
                    "idNumber",
                    models.CharField(max_length=25, verbose_name="TC Kimlik No"),
                ),
                ("adress", models.CharField(max_length=200, verbose_name="Adres")),
                ("tax", models.CharField(max_length=100, verbose_name="Vergi Dairesi")),
                ("mail1", models.EmailField(max_length=100, verbose_name="E-mail 1")),
                ("mail2", models.EmailField(max_length=100, verbose_name="E-mail 2")),
                (
                    "phoneNumber1",
                    models.CharField(max_length=20, verbose_name="Telefon 1"),
                ),
                (
                    "phoneNumber2",
                    models.CharField(max_length=20, verbose_name="Telefon 2"),
                ),
                ("IBAN", models.CharField(max_length=100, verbose_name="IBAN")),
                (
                    "bankNumber",
                    models.CharField(
                        max_length=100, verbose_name="Banka Hesap Numarası"
                    ),
                ),
                ("bank", models.CharField(max_length=100, verbose_name="Banka")),
                (
                    "companyName",
                    models.CharField(max_length=100, verbose_name="Şirket"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="kantar",
            name="nakliyat",
            field=models.CharField(
                choices=[("PP", "PP"), ("Ted", "Ted")],
                default="PP",
                max_length=100,
                verbose_name="Taşıma",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kantar",
            name="odeme",
            field=models.CharField(
                choices=[("EVET", "EVET"), ("HAYIR", "HAYIR")],
                default="EVET",
                max_length=100,
                verbose_name="Ödeme yapıldı mı?",
            ),
            preserve_default=False,
        ),
    ]
