# Generated by Django 4.2.2 on 2023-06-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0007_remove_alimlar_id_alimlar_alimkodu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alimlar_Kirilim",
            fields=[
                (
                    "alimKodu",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.FloatField(verbose_name="Ağırlık (kg)")),
                ("tarih", models.DateTimeField(verbose_name="Tarih")),
                ("birimFiyat", models.FloatField(verbose_name="Birim Fiyat")),
                (
                    "mal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.hammadde",
                        verbose_name="Malzeme Türü",
                    ),
                ),
                (
                    "tedarikEden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.tedarikci",
                        verbose_name="Tedarikçi",
                    ),
                ),
            ],
        ),
    ]
