# Generated by Django 4.1.3 on 2023-07-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0007_musteri_kantar_nakliyat_kantar_odeme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kantar",
            name="note",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Not"
            ),
        ),
    ]
