# Generated by Django 4.2.2 on 2023-06-17 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0008_alimlar_kirilim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimlar",
            name="tarih",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Tarih"
            ),
        ),
    ]
