# Generated by Django 4.1.3 on 2023-07-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0008_alter_kantar_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kantar",
            name="note",
            field=models.TextField(
                blank=True, max_length=180, null=True, verbose_name="Not"
            ),
        ),
    ]
