# Generated by Django 4.2.2 on 2023-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0009_alter_alimlar_tarih"),
    ]

    operations = [
        migrations.AddField(
            model_name="alimlar",
            name="alimKoduGenel",
            field=models.IntegerField(default=1, verbose_name="Alım Kodu"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alimlar_kirilim",
            name="alimKoduGenel",
            field=models.IntegerField(default=1, verbose_name="Alım Kodu"),
            preserve_default=False,
        ),
    ]
