# Generated by Django 4.2.2 on 2023-08-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0010_sonurun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Satis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.FloatField(verbose_name="Miktar")),
                (
                    "musteri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.musteri",
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "urunTipi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainPage.sonurun",
                        verbose_name="Ürün Tipi",
                    ),
                ),
            ],
        ),
    ]
