# Generated by Django 4.2.2 on 2023-06-20 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0010_alimlar_alimkodugenel_alimlar_kirilim_alimkodugenel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimlar_kirilim",
            name="tarih",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Tarih"
            ),
        ),
    ]
