# Generated by Django 4.1.3 on 2023-08-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0015_alter_malalim_odenecek"),
    ]

    operations = [
        migrations.AddField(
            model_name="kantar",
            name="faturaNo",
            field=models.TextField(blank=True, null=True, verbose_name="Fatura No"),
        ),
        migrations.AddField(
            model_name="kantar",
            name="faturaTarihi",
            field=models.DateField(blank=True, null=True, verbose_name="Fatura Tarihi"),
        ),
    ]
