# Generated by Django 4.1.3 on 2023-08-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0017_alter_kantar_faturatarihi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kantar",
            name="faturaTarihi",
            field=models.DateField(blank=True, null=True, verbose_name="Fatura Tarihi"),
        ),
    ]
