# Generated by Django 4.1.3 on 2023-08-26 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainPage",
            "0021_satis_birimfiyat_satis_faturano_satis_faturatarihi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="satis",
            name="satisTarihi",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Satış Tarihi"
            ),
        ),
    ]
