# Generated by Django 4.2.2 on 2023-08-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0022_alter_satis_satistarihi"),
    ]

    operations = [
        migrations.AddField(
            model_name="hammadde",
            name="category",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Mal Kategorisi"
            ),
        ),
    ]
