# Generated by Django 4.2.2 on 2023-08-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0023_hammadde_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hammadde",
            name="isScrap",
        ),
    ]
