# Generated by Django 4.2.2 on 2023-08-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0024_remove_hammadde_isscrap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tedarikci",
            name="bank",
        ),
        migrations.RemoveField(
            model_name="tedarikci",
            name="bankNumber",
        ),
        migrations.RemoveField(
            model_name="tedarikci",
            name="companyName",
        ),
        migrations.RemoveField(
            model_name="tedarikci",
            name="surname",
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="IBAN",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="IBAN"
            ),
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="adress",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Adres"
            ),
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="idNumber",
            field=models.CharField(
                max_length=25, verbose_name="TC Kimlik No / Vergi No"
            ),
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="mail1",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="E-mail 1"
            ),
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="mail2",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="E-mail 2"
            ),
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Ad Soyad / Şirket"),
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="phoneNumber1",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon 1"
            ),
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="phoneNumber2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon 2"
            ),
        ),
        migrations.AlterField(
            model_name="tedarikci",
            name="tax",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Vergi Dairesi"
            ),
        ),
    ]
