# Generated by Django 4.2.2 on 2023-08-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0025_remove_tedarikci_bank_remove_tedarikci_banknumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tedarikci",
            name="idNumber",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="TC Kimlik No / Vergi No",
            ),
        ),
    ]
